R29 Roadmap Update
etn-ccis/blui-database pull request #44
Opened 2023-08-01 09:30 UTC by ektaghag-eaton

Fixes 4441 .

#### Changes proposed in this Pull Request:

- R29 Roadmap Update
-
-

#### Screenshots / Screen Recording (if applicable)

-

#### To Test:

-

#### Any specific feedback you are looking for?

-

2023-08-01 09:43 UTC, surajeaton approved these changes
Looks good.

2023-08-01 14:11 UTC, huayunh requested changes
No changes for https://github.com/etn-ccis/blui-database/blob/dev/src/data/doc-it/R28Roadmap.ts ?

Please also read the readme file to learn what needs to be done to deploy these changes.

2023-08-02 13:28 UTC, huayunh requested changes

2023-08-02 13:28 UTC, huayunh commented on src/data/doc-it/R28Roadmap.ts
> +                status: 'finished',
why is this marked as finished?

2023-08-02 13:28 UTC, huayunh commented on src/data/doc-it/R29Roadmap.ts
> +        name: 'Design Guidelines',
I will take this bucket out completely. The DLM one has nothing to do with other developers, and I am confident there will be no "MD3 design guidelines"; probably only a component sticker sheet with tokens. 

For the future, I recommend avoiding acronyms like "MD3" "DLM" completely.

2023-08-02 13:28 UTC, huayunh commented on src/data/doc-it/R29Roadmap.ts
> +                description: 'Accessibility Support to Brightlayer Documentation site',
I don't know what this is.

2023-08-02 13:28 UTC, huayunh commented on src/data/doc-it/R29Roadmap.ts
> +                name: 'Templates & Examples Upgrades to latest',
I don't know what this is either. And there should not be a mix of sentence case and title case.

2023-08-02 13:28 UTC, huayunh commented on src/data/doc-it/R29Roadmap.ts
> +                name: 'React Dev Docs Phase 2',
I am not 100% confident that this can be done, but you can leave it here. However, I recommend:
1. avoid calling it dev doc or "phase 2"; the name makes no sense to adopters
2. articulate what new features is being added

2023-08-02 13:28 UTC, huayunh commented on src/data/doc-it/R29Roadmap.ts
> +                framework: ['react'],
improvement to docit is not a React exclusive thing. It's not like only React developers will be impacted by updates on docit.

2023-08-03 05:38 UTC, ektaghag-eaton commented on src/data/doc-it/R29Roadmap.ts
> +                description: 'Accessibility Support to Brightlayer Documentation site',
Check with Joe we don't need to update anything which has not started. So, removing it.

2023-08-03 05:39 UTC, ektaghag-eaton commented on src/data/doc-it/R29Roadmap.ts
> +                name: 'Templates & Examples Upgrades to latest',
Removing it.

2023-08-03 07:20 UTC, ektaghag-eaton commented on src/data/doc-it/R28Roadmap.ts
> +                status: 'finished',
@surajeaton, @daileytj please let me know if is it finished or not.

2023-08-03 12:23 UTC, huayunh commented on src/data/doc-it/R28Roadmap.ts
> +                status: 'finished',
This is not even started other than a proof of concept.

2023-08-03 12:51 UTC, ektaghag-eaton commented on src/data/doc-it/R28Roadmap.ts
> +                status: 'finished',
Oh Ok will revert changes

2023-08-03 21:39 UTC, huayunh approved these changes
overall looks fine.

2023-08-03 21:39 UTC, huayunh commented on src/data/doc-it/R29Roadmap.ts
> +        ],
I would not call themes "library" given we have only 2 themes.

And I would not call the thing "Material You". Material You is an aspect of Material Design 3. Call it Material Design 3 instead.

2023-08-04 05:57 UTC, merged